rl_alg_kwargs:
  ir_alg_kwargs: 
    lr: 0.0025
    batch_size: 64
    beta: $beta
wrappers:
 - FlattenObservation
 - DiaynSkillWrapper
wrappers_kwargs:
 - {}
 - skill_size: $skill_size
   use_discrete_skills: true
   skill_key: skill
   state_key: state
sweep_configuration:
  method: bayes
  parameters:
    beta:
      distribution: q_log_uniform_values
      q: 0.00001
      min: 0.001
      max: 1
    skill_size:
      distribution: int_uniform
      min: 3
      max: 20
sweep_count: 20