rl_alg_kwargs:
  ir_alg_kwargs: 
    latent_dim: 64
    lr: 0.002
    batch_size: 64
    lambd: $lambd
    beta: $beta
sweep_configuration:
  method: bayes
  parameters:
    beta:
      distribution: q_log_uniform_values
      q: 0.0001
      min: 0.0001
      max: 0.1
    lambd:
      distribution: q_log_uniform_values
      q: 0.001
      min: 0.001
      max: 0.1
sweep_count: 15
