rl_alg_kwargs:
  ir_alg_cls: girm
  ir_alg_kwargs:
    envs: envs
    latent_dim: 64
    lr: 0.002
    batch_size: 64
    lambd: 0.005
    beta: 0.004
    kappa: 0
experiment_prefix: cartpole_tuned_
experiment_suffix: _girm