rl_alg: PPO
rl_alg_kwargs:
  learning_rate: 0.00075
  n_steps: 2048
  batch_size: 256
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
experiment_prefix: novgrid_tuned_
experiment_suffix: ""