rl_alg: IR_PPO
rl_alg_kwargs:
  learning_rate: 0.001
  n_steps: 2048
  batch_size: 256
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  ir_alg_cls: diayn
  ir_alg_kwargs: 
    envs: envs
    device: torch_device
    lr: 0.001
    batch_size: 32
    beta: 1
    kappa: 0
experiment_suffix: _diayn
save_model: false
log: false
wrappers:
 - ImgObsWrapper
 - FlattenObservation
 - DiaynSkillWrapper