rl_alg_kwargs:
  ir_alg_cls: diayn
  ir_alg_kwargs: 
    envs: envs
    device: torch_device
    lr: 0.001
    batch_size: 32
    beta: 1
    kappa: 0
policy: MultiInputPolicy
experiment_suffix: _diayn
wrappers:
 - ImgObsWrapper
 - FlattenObservation
 - DiaynSkillWrapper