sweep_env_configs:
 - env_id: NovGrid-ColoredDoorKeyEnv
   door_color: red
   correct_key_color: red
   key_colors: 
   - red
 - env_id: MiniGrid-SimpleCrossingS9N3-v0
   num_crossings: 2
eval_freq: 2000
eval_episodes: 10
min_reward_threshold: 0.35
total_time_steps: 3000000
n_runs: 3
n_envs: 10
verbose: 1