rl_alg_kwargs:
  ir_alg_kwargs: 
    lr: $learning_rate
    batch_size: $batch_size
    beta: $beta
wrappers_kwargs:
 - {}
 - {}
 - skill_size: $skill_size
   use_discrete_skills: $use_discrete_skills
   skill_key: skill
   state_key: state
sweep_configuration:
  method: bayes
  parameters:
    beta:
      min: 0.00001
      max: 0.1
    learning_rate:
      min: 0.0001
      max: 0.01
    batch_size:
      values:
       - 16
       - 32
       - 64
    use_discrete_skills:
      values:
       - True
       - False
    skill_size:
      values:
       - 1
       - 3
       - 5
       - 7
       - 10
       - 12
       - 15
       - 20
sweep_count: 40