rl_alg_kwargs:
  ir_alg_kwargs: 
    lr: $learning_rate
    batch_size: $batch_size
    beta: $beta
wrappers_kwargs:
 - {}
 - {}
 - skill_size: $skill_size
   use_discrete_skills: $use_discrete_skills
   skill_key: skill
   state_key: state
sweep_configuration:
  method: bayes
  parameters:
    beta:
      distribution: q_log_uniform_values
      q: 0.00001
      min: 0.00001
      max: 0.1
    learning_rate:
      distribution: q_log_uniform_values
      q: 0.0001
      min: 0.0001
      max: 0.01
    batch_size:
      distribution: categorical
      values:
       - 16
       - 32
       - 64
    use_discrete_skills:
      distribution: categorical
      values:
       - True
       - False
    skill_size:
      distribution: int_uniform
      min: 3
      max: 20
sweep_count: 20