rl_alg_kwargs:
  ir_alg_kwargs: 
    lr: $learning_rate
    batch_size: $batch_size
    beta: $beta
sweep_configuration:
  method: bayes
  parameters:
    beta:
      distribution: q_log_uniform
      q: 0.00001
      min: 0.00001
      max: 0.1
    learning_rate:
      distribution: q_log_uniform
      q: 0.0001
      min: 0.0001
      max: 0.01
    batch_size:
      distribution: categorical
      values:
       - 16
       - 32
       - 64
sweep_count: 20