rl_alg_kwargs:
  ir_alg_kwargs: 
    latent_dim: $latent_dim
    lr: $learning_rate
    batch_size: $batch_size
    beta: $beta
sweep_configuration:
  method: bayes
  parameters:
    beta:
      distribution: q_log_uniform_values
      q: 0.0001
      min: 0.0001
      max: 0.5
    learning_rate:
      distribution: q_log_uniform_values
      q: 0.0001
      min: 0.0001
      max: 0.01
    batch_size:
      distribution: categorical
      values:
       - 16
       - 32
       - 64
    latent_dim:
      distribution: categorical
      values:
       - 16
       - 32
       - 64
       - 128
       - 256
sweep_count: 30