rl_alg_kwargs:
  learning_rate: $learning_rate
sweep_configuration:
  method: bayes
  parameters:
    learning_rate:
      distribution: q_uniform
      q: 0.00001
      min: 0.0003
      max: 0.0008
sweep_count: 20